//creates content packs
const fs = require('fs');

//gender: 0 - male, 1 - female
const names = [
    // USA
  {name: 'James', gender: 0, nation: 'usa'},
  {name: 'Emma', gender: 1, nation: 'usa'},
  {name: 'Liam', gender: 0, nation: 'usa'},
  {name: 'Olivia', gender: 1, nation: 'usa'},
  {name: 'Noah', gender: 0, nation: 'usa'},
  {name: 'Ava', gender: 1, nation: 'usa'},
  {name: 'William', gender: 0, nation: 'usa'},
  {name: 'Sophia', gender: 1, nation: 'usa'},
  {name: 'Logan', gender: 0, nation: 'usa'},
  {name: 'Isabella', gender: 1, nation: 'usa'},
  {name: 'Benjamin', gender: 0, nation: 'usa'},
  {name: 'Mia', gender: 1, nation: 'usa'},
  {name: 'Elijah', gender: 0, nation: 'usa'},
  {name: 'Charlotte', gender: 1, nation: 'usa'},
  {name: 'Mason', gender: 0, nation: 'usa'},
  
  // Russia
  {name: 'Alexander', gender: 0, nation: 'russia'},
  {name: 'Sofia', gender: 1, nation: 'russia'},
  {name: 'Maxim', gender: 0, nation: 'russia'},
  {name: 'Anastasia', gender: 1, nation: 'russia'},
  {name: 'Artem', gender: 0, nation: 'russia'},
  {name: 'Maria', gender: 1, nation: 'russia'},
  {name: 'Dmitri', gender: 0, nation: 'russia'},
  {name: 'Natalia', gender: 1, nation: 'russia'},
  {name: 'Ivan', gender: 0, nation: 'russia'},
  {name: 'Yelena', gender: 1, nation: 'russia'},
  {name: 'Andrei', gender: 0, nation: 'russia'},
  {name: 'Tatiana', gender: 1, nation: 'russia'},
  {name: 'Nikolai', gender: 0, nation: 'russia'},
  {name: 'Oksana', gender: 1, nation: 'russia'},
  {name: 'Sergei', gender: 0, nation: 'russia'},
  
  // Mexico
  {name: 'Santiago', gender: 0, nation: 'mexico'},
  {name: 'Valentina', gender: 1, nation: 'mexico'},
  {name: 'Mateo', gender: 0, nation: 'mexico'},
  {name: 'Camila', gender: 1, nation: 'mexico'},
  {name: 'Diego', gender: 0, nation: 'mexico'},
  {name: 'Renata', gender: 1, nation: 'mexico'},
  {name: 'Carlos', gender: 0, nation: 'mexico'},
  {name: 'Isabella', gender: 1, nation: 'mexico'},
  {name: 'Joaquin', gender: 0, nation: 'mexico'},
  {name: 'Valeria', gender: 1, nation: 'mexico'},
  {name: 'Luis', gender: 0, nation: 'mexico'},
  {name: 'Elena', gender: 1, nation: 'mexico'},
  {name: 'Alejandro', gender: 0, nation: 'mexico'},
  {name: 'Ximena', gender: 1, nation: 'mexico'},
  {name: 'Fernanda', gender: 1, nation: 'mexico'},
  
  // Italy
  {name: 'Lorenzo', gender: 0, nation: 'italy'},
  {name: 'Sofia', gender: 1, nation: 'italy'},
  {name: 'Alessandro', gender: 0, nation: 'italy'},
  {name: 'Giulia', gender: 1, nation: 'italy'},
  {name: 'Matteo', gender: 0, nation: 'italy'},
  {name: 'Isabella', gender: 1, nation: 'italy'},
  {name: 'Francesco', gender: 0, nation: 'italy'},
  {name: 'Alice', gender: 1, nation: 'italy'},
  {name: 'Davide', gender: 0, nation: 'italy'},
  {name: 'Sophia', gender: 1, nation: 'italy'},
  {name: 'Gabriele', gender: 0, nation: 'italy'},
  {name: 'Aurora', gender: 1, nation: 'italy'},
  {name: 'Marco', gender: 0, nation: 'italy'},
  {name: 'Martina', gender: 1, nation: 'italy'},
  {name: 'Emanuele', gender: 0, nation: 'italy'},
  
  // France
  {name: 'Louis', gender: 0, nation: 'france'},
  {name: 'Emma', gender: 1, nation: 'france'},
  {name: 'Pierre', gender: 0, nation: 'france'},
  {name: 'Camille', gender: 1, nation: 'france'},
  {name: 'Antoine', gender: 0, nation: 'france'},
  {name: 'Charlotte', gender: 1, nation: 'france'},
  {name: 'Lucas', gender: 0, nation: 'france'},
  {name: 'Sophie', gender: 1, nation: 'france'},
  {name: 'Hugo', gender: 0, nation: 'france'},
  {name: 'Chloe', gender: 1, nation: 'france'},
  {name: 'Gabriel', gender: 0, nation: 'france'},
  {name: 'Juliette', gender: 1, nation: 'france'},
  {name: 'Mathis', gender: 0, nation: 'france'},
  {name: 'Léa', gender: 1, nation: 'france'},
  {name: 'Raphael', gender: 0, nation: 'france'},
  
  // Spain
  {name: 'Santiago', gender: 0, nation: 'spain'},
  {name: 'Maria', gender: 1, nation: 'spain'},
  {name: 'Alejandro', gender: 0, nation: 'spain'},
  {name: 'Lucia', gender: 1, nation: 'spain'},
  {name: 'Daniel', gender: 0, nation: 'spain'},
  {name: 'Paula', gender: 1, nation: 'spain'},
  {name: 'Pablo', gender: 0, nation: 'spain'},
  {name: 'Sofia', gender: 1, nation: 'spain'},
  {name: 'Mateo', gender: 0, nation: 'spain'},
  {name: 'Valentina', gender: 1, nation: 'spain'},
  {name: 'Adrian', gender: 0, nation: 'spain'},
  {name: 'Marta', gender: 1, nation: 'spain'},
  {name: 'Javier', gender: 0, nation: 'spain'},
  {name: 'Emma', gender: 1, nation: 'spain'},
  {name: 'Diego', gender: 0, nation: 'spain'},
  
  // China
  {name: 'Wei', gender: 0, nation: 'china'},
  {name: 'Li', gender: 0, nation: 'china'},
  {name: 'Yan', gender: 0, nation: 'china'},
  {name: 'Xiu', gender: 1, nation: 'china'},
  {name: 'Tao', gender: 0, nation: 'china'},
  {name: 'Mei', gender: 1, nation: 'china'},
  {name: 'Jing', gender: 0, nation: 'china'},
  {name: 'Hui', gender: 1, nation: 'china'},
  {name: 'Shan', gender: 0, nation: 'china'},
  {name: 'Xia', gender: 1, nation: 'china'},
  {name: 'Liang', gender: 0, nation: 'china'},
  {name: 'Yu', gender: 1, nation: 'china'},
  {name: 'Chen', gender: 0, nation: 'china'},
  {name: 'Lan', gender: 1, nation: 'china'},
  {name: 'Bo', gender: 0, nation: 'china'},
  
  // Japan
  {name: 'Hiroshi', gender: 0, nation: 'japan'},
  {name: 'Aoi', gender: 1, nation: 'japan'},
  {name: 'Takashi', gender: 0, nation: 'japan'},
  {name: 'Sakura', gender: 1, nation: 'japan'},
  {name: 'Kazuki', gender: 0, nation: 'japan'},
  {name: 'Yuki', gender: 1, nation: 'japan'},
  {name: 'Haruki', gender: 0, nation: 'japan'},
  {name: 'Hana', gender: 1, nation: 'japan'},
  {name: 'Ryo', gender: 0, nation: 'japan'},
  {name: 'Nao', gender: 1, nation: 'japan'},
  {name: 'Keisuke', gender: 0, nation: 'japan'},
  {name: 'Miku', gender: 1, nation: 'japan'},
  {name: 'Kaito', gender: 0, nation: 'japan'},
  {name: 'Ami', gender: 1, nation: 'japan'},
  {name: 'Daiki', gender: 0, nation: 'japan'},
  
  // England
  {name: 'William', gender: 0, nation: 'england'},
  {name: 'Olivia', gender: 1, nation: 'england'},
  {name: 'George', gender: 0, nation: 'england'},
  {name: 'Charlotte', gender: 1, nation: 'england'},
  {name: 'Harry', gender: 0, nation: 'england'},
  {name: 'Amelia', gender: 1, nation: 'england'},
  {name: 'James', gender: 0, nation: 'england'},
  {name: 'Sophia', gender: 1, nation: 'england'},
  {name: 'Alexander', gender: 0, nation: 'england'},
  {name: 'Lily', gender: 1, nation: 'england'},
  {name: 'Henry', gender: 0, nation: 'england'},
  {name: 'Isabella', gender: 1, nation: 'england'},
  {name: 'Edward', gender: 0, nation: 'england'},
  {name: 'Mia', gender: 1, nation: 'england'},
  {name: 'Charlotte', gender: 1, nation: 'england'},
  
  // India
  {name: 'Aarav', gender: 0, nation: 'india'},
  {name: 'Saanvi', gender: 1, nation: 'india'},
  {name: 'Aryan', gender: 0, nation: 'india'},
  {name: 'Myra', gender: 1, nation: 'india'},
  {name: 'Vivaan', gender: 0, nation: 'india'},
  {name: 'Diya', gender: 1, nation: 'india'},
  {name: 'Ishaan', gender: 0, nation: 'india'},
  {name: 'Aadhya', gender: 1, nation: 'india'},
  {name: 'Arjun', gender: 0, nation: 'india'},
  {name: 'Ananya', gender: 1, nation: 'india'},
  {name: 'Kabir', gender: 0, nation: 'india'},
  {name: 'Pari', gender: 1, nation: 'india'},
  {name: 'Rudra', gender: 0, nation: 'india'},
  {name: 'Avni', gender: 1, nation: 'india'},
  {name: 'Reeva', gender: 1, nation: 'india'},
]

const surnames = [
    // USA
  {name: 'Smith', nation: 'usa'},
  {name: 'Johnson', nation: 'usa'},
  {name: 'Williams', nation: 'usa'},
  {name: 'Jones', nation: 'usa'},
  {name: 'Brown', nation: 'usa'},
  {name: 'Davis', nation: 'usa'},
  {name: 'Miller', nation: 'usa'},
  {name: 'Wilson', nation: 'usa'},
  {name: 'Moore', nation: 'usa'},
  {name: 'Taylor', nation: 'usa'},
  {name: 'Anderson', nation: 'usa'},
  {name: 'Thomas', nation: 'usa'},
  {name: 'Jackson', nation: 'usa'},
  {name: 'White', nation: 'usa'},
  {name: 'Harris', nation: 'usa'},
  
  // Russia
  {name: 'Ivanov', nation: 'russia'},
  {name: 'Smirnov', nation: 'russia'},
  {name: 'Kuznetsov', nation: 'russia'},
  {name: 'Popov', nation: 'russia'},
  {name: 'Sokolov', nation: 'russia'},
  {name: 'Mikhailov', nation: 'russia'},
  {name: 'Petrov', nation: 'russia'},
  {name: 'Fedorov', nation: 'russia'},
  {name: 'Morozov', nation: 'russia'},
  {name: 'Volkov', nation: 'russia'},
  {name: 'Lebedev', nation: 'russia'},
  {name: 'Semenov', nation: 'russia'},
  {name: 'Egorov', nation: 'russia'},
  {name: 'Nikitin', nation: 'russia'},
  {name: 'Kozlov', nation: 'russia'},
  
  // Mexico
  {name: 'Garcia', nation: 'mexico'},
  {name: 'Rodriguez', nation: 'mexico'},
  {name: 'Hernandez', nation: 'mexico'},
  {name: 'Lopez', nation: 'mexico'},
  {name: 'Martinez', nation: 'mexico'},
  {name: 'Gonzalez', nation: 'mexico'},
  {name: 'Perez', nation: 'mexico'},
  {name: 'Sanchez', nation: 'mexico'},
  {name: 'Torres', nation: 'mexico'},
  {name: 'Ramirez', nation: 'mexico'},
  {name: 'Diaz', nation: 'mexico'},
  {name: 'Jimenez', nation: 'mexico'},
  {name: 'Moreno', nation: 'mexico'},
  {name: 'Castillo', nation: 'mexico'},
  {name: 'Vargas', nation: 'mexico'},
  
  // Italy
  {name: 'Rossi', nation: 'italy'},
  {name: 'Russo', nation: 'italy'},
  {name: 'Ferrari', nation: 'italy'},
  {name: 'Esposito', nation: 'italy'},
  {name: 'Bianchi', nation: 'italy'},
  {name: 'Romano', nation: 'italy'},
  {name: 'Gallo', nation: 'italy'},
  {name: 'Conti', nation: 'italy'},
  {name: 'Costa', nation: 'italy'},
  {name: 'Mancini', nation: 'italy'},
  {name: 'Leone', nation: 'italy'},
  {name: 'Greco', nation: 'italy'},
  {name: 'Santoro', nation: 'italy'},
  {name: 'Lombardi', nation: 'italy'},
  {name: 'Barbieri', nation: 'italy'},
  
  // France
  {name: 'Martin', nation: 'france'},
  {name: 'Dubois', nation: 'france'},
  {name: 'Thomas', nation: 'france'},
  {name: 'Lefebvre', nation: 'france'},
  {name: 'Dupont', nation: 'france'},
  {name: 'Moreau', nation: 'france'},
  {name: 'Leroy', nation: 'france'},
  {name: 'Lambert', nation: 'france'},
  {name: 'Fontaine', nation: 'france'},
  {name: 'Roux', nation: 'france'},
  {name: 'Girard', nation: 'france'},
  {name: 'Muller', nation: 'france'},
  {name: 'Fournier', nation: 'france'},
  {name: 'Garnier', nation: 'france'},
  {name: 'Henry', nation: 'france'},
  
  // Spain
  {name: 'Garcia', nation: 'spain'},
  {name: 'Rodriguez', nation: 'spain'},
  {name: 'Fernandez', nation: 'spain'},
  {name: 'Lopez', nation: 'spain'},
  {name: 'Martinez', nation: 'spain'},
  {name: 'Sanchez', nation: 'spain'},
  {name: 'Perez', nation: 'spain'},
  {name: 'Gomez', nation: 'spain'},
  {name: 'Gonzalez', nation: 'spain'},
  {name: 'Romero', nation: 'spain'},
  {name: 'Herrera', nation: 'spain'},
  {name: 'Diaz', nation: 'spain'},
  {name: 'Alvarez', nation: 'spain'},
  {name: 'Torres', nation: 'spain'},
  {name: 'Ramos', nation: 'spain'},
  
  // China
  {name: 'Li', nation: 'china'},
  {name: 'Wang', nation: 'china'},
  {name: 'Zhang', nation: 'china'},
  {name: 'Liu', nation: 'china'},
  {name: 'Chen', nation: 'china'},
  {name: 'Yang', nation: 'china'},
  {name: 'Huang', nation: 'china'},
  {name: 'Zhao', nation: 'china'},
  {name: 'Wu', nation: 'china'},
  {name: 'Zhou', nation: 'china'},
  {name: 'Xu', nation: 'china'},
  {name: 'Sun', nation: 'china'},
  {name: 'Ma', nation: 'china'},
  {name: 'Hu', nation: 'china'},
  {name: 'Gao', nation: 'china'},
  
  // Japan
  {name: 'Sato', nation: 'japan'},
  {name: 'Suzuki', nation: 'japan'},
  {name: 'Takahashi', nation: 'japan'},
  {name: 'Tanaka', nation: 'japan'},
  {name: 'Watanabe', nation: 'japan'},
  {name: 'Ito', nation: 'japan'},
  {name: 'Yamamoto', nation: 'japan'},
  {name: 'Nakamura', nation: 'japan'},
  {name: 'Kobayashi', nation: 'japan'},
  {name: 'Kato', nation: 'japan'},
  {name: 'Yoshida', nation: 'japan'},
  {name: 'Yamada', nation: 'japan'},
  {name: 'Sasaki', nation: 'japan'},
  {name: 'Yamaguchi', nation: 'japan'},
  {name: 'Matsumoto', nation: 'japan'},
  
  // England
  {name: 'Smith', nation: 'england'},
  {name: 'Jones', nation: 'england'},
  {name: 'Taylor', nation: 'england'},
  {name: 'Williams', nation: 'england'},
  {name: 'Brown', nation: 'england'},
  {name: 'Davies', nation: 'england'},
  {name: 'Evans', nation: 'england'},
  {name: 'Wilson', nation: 'england'},
  {name: 'Thomas', nation: 'england'},
  {name: 'Harris', nation: 'england'},
  {name: 'Roberts', nation: 'england'},
  {name: 'Clark', nation: 'england'},
  {name: 'Wright', nation: 'england'},
  {name: 'Walker', nation: 'england'},
  {name: 'King', nation: 'england'},
  
  // India
  {name: 'Kumar', nation: 'india'},
  {name: 'Patel', nation: 'india'},
  {name: 'Sharma', nation: 'india'},
  {name: 'Gupta', nation: 'india'},
  {name: 'Singh', nation: 'india'},
  {name: 'Yadav', nation: 'india'},
  {name: 'Verma', nation: 'india'},
  {name: 'Rao', nation: 'india'},
  {name: 'Joshi', nation: 'india'},
  {name: 'Kaur', nation: 'india'},
  {name: 'Das', nation: 'india'},
  {name: 'Acharya', nation: 'india'},
  {name: 'Reddy', nation: 'india'},
  {name: 'Mishra', nation: 'india'},
  {name: 'Malik', nation: 'india'},
]

const idea_blocks = [
    {block: '[protagonist] is a cop,', setting: 'modern_day'},
]

/* {type: 'one-of-set-types', 
    content: 'the action itself were stuff in [] will be replaced in script-gen time',
    intensity: 'a number between 0 and 1 which is the intensity the scenario will usually play with some margin of error. Use exactly 0 to make the scenario possible for every intensity'
    combo_name: 'name/id of the combination this belongs to. leave blank to make it separate',
    combo_i: 'the index of the scenario in the combination. Set to 0 if combo-name is blank'}
*/
let scenarios = {
    environment: [
        //mandatory
        {type: 'environment', content: 'LOAD MAP:[map]', intensity: 0.0, combo_name: '', combo_i: 0},
        {type: 'environment', content: 'CHANGE MAP STATE:[map-state]', intensity: 0.0, combo_name: '', combo_i: 0},
        //added
        {type: 'environment', content: 'EXPLODE SMALL:[target]', intensity: 0.66, combo_name: '', combo_i: 0},
        {type: 'environment', content: 'EXPLODE MEDIUM:[target]', intensity: 0.66, combo_name: '', combo_i: 0},
        {type: 'environment', content: 'EXPLODE LARGE:[target]', intensity: 0.66, combo_name: '', combo_i: 0},
        {type: 'environment', content: 'DESTROY:[map-prop]', intensity: 0.5, combo_name: '', combo_i: 0},
    ],
    cinematographer: [
        //transition between shots changer
        {type: 'cinematographer', content: 'Transition>>smooth', intensity: 0.0, combo_name: '', combo_i: 0},
        {type: 'cinematographer', content: 'Transition>>linear', intensity: 0.0, combo_name: '', combo_i: 0},
        {type: 'cinematographer', content: 'Transition>>instant', intensity: 0.0, combo_name: '', combo_i: 0},
        //shots
        {type: 'cinematographer', content: 'Camera>>top down view', intensity: 0.0, combo_name: '', combo_i: 0},
        {type: 'cinematographer', content: 'Camera>>top down view follow:[target]', intensity: 0.0, combo_name: '', combo_i: 0},
        {type: 'cinematographer', content: 'Camera>>left side view follow:[target]', intensity: 0.0, combo_name: '', combo_i: 0},
        {type: 'cinematographer', content: 'Camera>>right side view follow:[target]', intensity: 0.0, combo_name: '', combo_i: 0},
        {type: 'cinematographer', content: 'Camera>>front side view follow:[target]', intensity: 0.0, combo_name: '', combo_i: 0},
        {type: 'cinematographer', content: 'Camera>>back side view follow:[target]', intensity: 0.0, combo_name: '', combo_i: 0},
        {type: 'cinematographer', content: 'Camera>>close up head front-under:[target]', intensity: 0.0, combo_name: '', combo_i: 0},
        {type: 'cinematographer', content: 'Camera>>close up head front-above:[target]', intensity: 0.0, combo_name: '', combo_i: 0},
        {type: 'cinematographer', content: 'Camera>>close up head profile-left:[target]', intensity: 0.0, combo_name: '', combo_i: 0},
        {type: 'cinematographer', content: 'Camera>>close up head profile-right:[target]', intensity: 0.0, combo_name: '', combo_i: 0},
        {type: 'cinematographer', content: 'Camera>>close up head side-left:[target]', intensity: 0.0, combo_name: '', combo_i: 0},
        {type: 'cinematographer', content: 'Camera>>close up head side-right:[target]', intensity: 0.0, combo_name: '', combo_i: 0},
        {type: 'cinematographer', content: 'Camera>>center whole body front:[target]', intensity: 0.0, combo_name: '', combo_i: 0},
        {type: 'cinematographer', content: 'Camera>>center whole body profile-left:[target]', intensity: 0.0, combo_name: '', combo_i: 0},
        {type: 'cinematographer', content: 'Camera>>center whole body profile-right:[target]', intensity: 0.0, combo_name: '', combo_i: 0},
        {type: 'cinematographer', content: 'Camera>>rule of three left:[target-1]&[target-2]', intensity: 0.25, combo_name: '', combo_i: 0},
        {type: 'cinematographer', content: 'Camera>>rule of three right:[target-1]&[target-2]', intensity: 0.25, combo_name: '', combo_i: 0},
        {type: 'cinematographer', content: 'Camera>>wide shot side-left:[target]', intensity: 0.33, combo_name: '', combo_i: 0},
        {type: 'cinematographer', content: 'Camera>>wide shot side-right:[target]', intensity: 0.33, combo_name: '', combo_i: 0},
        {type: 'cinematographer', content: 'Camera>>wide shot side-front:[target]', intensity: 0.33, combo_name: '', combo_i: 0},
        {type: 'cinematographer', content: 'Camera>>wide shot side-back:[target]', intensity: 0.33, combo_name: '', combo_i: 0},
        {type: 'cinematographer', content: 'Camera>>wide shot spin-clockwise:[target]', intensity: 0.33, combo_name: '', combo_i: 0},
        {type: 'cinematographer', content: 'Camera>>wide shot spin-c-clockwise:[target]', intensity: 0.33, combo_name: '', combo_i: 0},
        {type: 'cinematographer', content: 'Camera>>zoom in focus:[target]', intensity: 0.2, combo_name: '', combo_i: 0},
        {type: 'cinematographer', content: 'Camera>>zoom out focus:[target]', intensity: 0.2, combo_name: '', combo_i: 0},
        {type: 'cinematographer', content: 'Camera>>pan left:[target]', intensity: 0.15, combo_name: '', combo_i: 0},
        {type: 'cinematographer', content: 'Camera>>pan right:[target]', intensity: 0.15, combo_name: '', combo_i: 0},
        {type: 'cinematographer', content: 'Camera>>dolly back:[target]', intensity: 0.3, combo_name: '', combo_i: 0},
        {type: 'cinematographer', content: 'Camera>>dolly forward:[target]', intensity: 0.3, combo_name: '', combo_i: 0},
        {type: 'cinematographer', content: 'Camera>>tilt up:[target]', intensity: 0.1, combo_name: '', combo_i: 0},
        {type: 'cinematographer', content: 'Camera>>tilt down:[target]', intensity: 0.1, combo_name: '', combo_i: 0},
        {type: 'cinematographer', content: 'Camera>>zoom in focus:[target]', intensity: 0.2, combo_name: '', combo_i: 0},
        {type: 'cinematographer', content: 'Camera>>zoom out focus:[target]', intensity: 0.2, combo_name: '', combo_i: 0},
        {type: 'cinematographer', content: 'Camera>>aerial shot', intensity: 0.2, combo_name: '', combo_i: 0},
        {type: 'cinematographer', content: 'Camera>>dutch angle left:[target]', intensity: 0.15, combo_name: '', combo_i: 0},
        {type: 'cinematographer', content: 'Camera>>dutch angle right:[target]', intensity: 0.15, combo_name: '', combo_i: 0},
        {type: 'cinematographer', content: 'Camera>>over the shoulder:[target]', intensity: 0.15, combo_name: '', combo_i: 0},
        {type: 'cinematographer', content: 'Camera>>point of view:[target]', intensity: 0.15, combo_name: '', combo_i: 0},
        {type: 'cinematographer', content: 'Camera>>tracking shot:[target]', intensity: 0.25, combo_name: '', combo_i: 0},
        {type: 'cinematographer', content: 'Camera>>low angle shot:[target]', intensity: 0.15, combo_name: '', combo_i: 0},
        {type: 'cinematographer', content: 'Camera>>high angle shot:[target]', intensity: 0.15, combo_name: '', combo_i: 0},
        //DoF focus
        {type: 'cinematographer', content: 'Camera>>clear focus:[target]', intensity: 0.1, combo_name: '', combo_i: 0},
        {type: 'cinematographer', content: 'Camera>>soft focus:[target]', intensity: 0.1, combo_name: '', combo_i: 0},
        {type: 'cinematographer', content: 'Camera>>deep focus:[target]', intensity: 0.15, combo_name: '', combo_i: 0},
        {type: 'cinematographer', content: 'Camera>>forward rack focus', intensity: 0.2, combo_name: '', combo_i: 0},
        {type: 'cinematographer', content: 'Camera>>backward rack focus', intensity: 0.2, combo_name: '', combo_i: 0},
        //scene transition
        {type: 'cinematographer', content: 'SceneTransition>>dissolve transition', intensity: 0.1, combo_name: '', combo_i: 0},
        {type: 'cinematographer', content: 'SceneTransition>>fade to black transition', intensity: 0.1, combo_name: '', combo_i: 0},
        {type: 'cinematographer', content: 'SceneTransition>>wipe transition', intensity: 0.1, combo_name: '', combo_i: 0},
        {type: 'cinematographer', content: 'SceneTransition>>cut to black transition', intensity: 0.1, combo_name: '', combo_i: 0},
        {type: 'cinematographer', content: 'SceneTransition>>match cut transition', intensity: 0.1, combo_name: '', combo_i: 0},
        {type: 'cinematographer', content: 'SceneTransition>>cross dissolve transition', intensity: 0.1, combo_name: '', combo_i: 0}
    ],
    audio: [
        //music
        {type: 'audio', content: 'Audio<<Play random calm background music', intensity: 0.01, combo_name: '', combo_i: 0},
        {type: 'audio', content: 'Audio<<Play random buildup background music', intensity: 0.33, combo_name: '', combo_i: 0},
        {type: 'audio', content: 'Audio<<Play random intense background music', intensity: 0.5, combo_name: '', combo_i: 0},
        {type: 'audio', content: 'Audio<<Play random fight-scene background music', intensity: 0.66, combo_name: '', combo_i: 0},
        {type: 'audio', content: 'Audio<<Play random climax background music', intensity: 0.9, combo_name: '', combo_i: 0},
        {type: 'audio', content: 'Audio<<Play random comedic background music', intensity: 0.2, combo_name: '', combo_i: 0},
        {type: 'audio', content: 'Audio<<Play random comedic-intense background music', intensity: 0.66, combo_name: '', combo_i: 0},
        {type: 'audio', content: 'Audio<<Play random sad background music', intensity: 0.3, combo_name: '', combo_i: 0},
        {type: 'audio', content: 'Audio<<Play random touching background music', intensity: 0.66, combo_name: '', combo_i: 0},
        //music control
        {type: 'audio', content: 'Audio<<Set volume low', intensity: 0.0, combo_name: '', combo_i: 0}, //allows voices to be heard
        {type: 'audio', content: 'Audio<<Set volume medium', intensity: 0.0, combo_name: '', combo_i: 0}, //mix where you can hear SFX and stuff
        {type: 'audio', content: 'Audio<<Set volume high', intensity: 0.0, combo_name: '', combo_i: 0}, //very loud
    ]
}

fs.writeFile('content/action/names.json', JSON.stringify(names), 'utf-8', (err) => {
    if(err) console.log(err)
    else console.log('written names')
})
fs.writeFile('content/action/surnames.json', JSON.stringify(surnames), 'utf-8', (err) => {
    if(err) console.log(err)
    else console.log('written surnames')
})
fs.writeFile('content/action/scenarios.json', JSON.stringify(scenarios), 'utf-8', (err) => {
    if(err) console.log(err)
    else console.log('written all scenarios')
})
fs.writeFile('content/action/ideablocks.json', JSON.stringify(scenarios), 'utf-8', (err) => {
    if(err) console.log(err)
    else console.log('written all scenarios')
})