//creates content packs
const fs = require('fs');

//gender: 0 - male, 1 - female
let names = [
    {name: 'Alexander', gender: 0, nation: 'usa'},
    {name: 'Bianca', gender: 1, nation: 'italy'},
    {name: 'Carlos', gender: 0, nation: 'mexico'},
    {name: 'Dmitri', gender: 0, nation: 'russia'},
    {name: 'Elena', gender: 1, nation: 'greece'},
    {name: 'Federico', gender: 0, nation: 'spain'},
    {name: 'Gianna', gender: 1, nation: 'usa'},
    {name: 'Hugo', gender: 0, nation: 'france'},
    {name: 'Isabella', gender: 1, nation: 'brazil'},
    {name: 'Javier', gender: 0, nation: 'mexico'},
    {name: 'Katerina', gender: 1, nation: 'russia'},
    {name: 'Lorenzo', gender: 0, nation: 'italy'},
    {name: 'Mia', gender: 1, nation: 'usa'},
    {name: 'Nikolai', gender: 0, nation: 'russia'},
    {name: 'Olivia', gender: 1, nation: 'usa'},
    {name: 'Pablo', gender: 0, nation: 'mexico'},
    {name: 'Quintin', gender: 0, nation: 'usa'},
    {name: 'Rosalie', gender: 1, nation: 'france'},
    {name: 'Sebastian', gender: 0, nation: 'spain'},
    {name: 'Tatiana', gender: 1, nation: 'russia'},
    {name: 'Uriel', gender: 0, nation: 'israel'},
    {name: 'Valentina', gender: 1, nation: 'italy'},
    {name: 'William', gender: 0, nation: 'england'},
    {name: 'Ximena', gender: 1, nation: 'mexico'},
    {name: 'Yuri', gender: 0, nation: 'russia'},
    {name: 'Zara', gender: 1, nation: 'india'},
    {name: 'Akira', gender: 0, nation: 'japan'},
    {name: 'Bai', gender: 0, nation: 'china'},
    {name: 'Chen', gender: 0, nation: 'china'},
    {name: 'Emi', gender: 1, nation: 'japan'},
    {name: 'Hiroshi', gender: 0, nation: 'japan'},
    {name: 'Jing', gender: 1, nation: 'china'},
    {name: 'Kenji', gender: 0, nation: 'japan'},
    {name: 'Li Wei', gender: 0, nation: 'china'},
    {name: 'Mao', gender: 0, nation: 'china'},
    {name: 'Nori', gender: 0, nation: 'japan'},
    {name: 'Qing', gender: 1, nation: 'china'},
    {name: 'Rin', gender: 1, nation: 'japan'},
    {name: 'Shan', gender: 1, nation: 'china'},
    {name: 'Takashi', gender: 0, nation: 'japan'},
    {name: 'Wei', gender: 0, nation: 'china'},
    {name: 'Xiao', gender: 0, nation: 'china'},
    {name: 'Yuki', gender: 1, nation: 'japan'},
    {name: 'Ziyi', gender: 1, nation: 'china'},
    {name: 'Aiden', gender: 0, nation: 'usa'},
    {name: 'Brooklyn', gender: 1, nation: 'usa'},
    {name: 'Cameron', gender: 0, nation: 'usa'},
    {name: 'Daisy', gender: 1, nation: 'usa'},
    {name: 'Elijah', gender: 0, nation: 'usa'},
    {name: 'Faith', gender: 1, nation: 'usa'},
    {name: 'Gabriel', gender: 0, nation: 'usa'},
    {name: 'Hannah', gender: 1, nation: 'usa'},
    {name: 'Isaac', gender: 0, nation: 'usa'},
    {name: 'Julia', gender: 1, nation: 'usa'},
    {name: 'Kevin', gender: 0, nation: 'usa'},
    {name: 'Lily', gender: 1, nation: 'usa'},
    {name: 'Mason', gender: 0, nation: 'usa'},
    {name: 'Natalie', gender: 1, nation: 'usa'},
    {name: 'Owen', gender: 0, nation: 'usa'},
    {name: 'Peyton', gender: 1, nation: 'usa'},
    {name: 'Quinn', gender: 0, nation: 'usa'},
    {name: 'Rachel', gender: 1, nation: 'usa'},
    {name: 'Samuel', gender: 0, nation: 'usa'},
    {name: 'Taylor', gender: 0, nation: 'usa'},
    {name: 'Ulysses', gender: 0, nation: 'usa'},
    {name: 'Victoria', gender: 1, nation: 'usa'},
    {name: 'William', gender: 0, nation: 'usa'},
    {name: 'Xander', gender: 0, nation: 'usa'},
    {name: 'Yasmine', gender: 1, nation: 'usa'},
    {name: 'Zane', gender: 0, nation: 'usa'}
]

let surnames = [
    {name: 'Smith', nation: 'usa'},
    {name: 'Garcia', nation: 'mexico'},
    {name: 'Wang', nation: 'china'},
    {name: 'Ivanov', nation: 'russia'},
    {name: 'Martinez', nation: 'mexico'},
    {name: 'Lopez', nation: 'mexico'},
    {name: 'Kim', nation: 'korea'},
    {name: 'Brown', nation: 'usa'},
    {name: 'Li', nation: 'china'},
    {name: 'Rodriguez', nation: 'mexico'},
    {name: 'Chen', nation: 'china'},
    {name: 'Takahashi', nation: 'japan'},
    {name: 'Santos', nation: 'brazil'},
    {name: 'Gupta', nation: 'india'},
    {name: 'Jackson', nation: 'usa'},
    {name: 'Mueller', nation: 'germany'},
    {name: 'Nguyen', nation: 'vietnam'},
    {name: 'Santoro', nation: 'italy'},
    {name: 'Chavez', nation: 'mexico'},
    {name: 'Lam', nation: 'china'},
    {name: 'Hernandez', nation: 'mexico'},
    {name: 'Johnson', nation: 'usa'},
    {name: 'Gomez', nation: 'mexico'},
    {name: 'Patel', nation: 'india'},
    {name: 'Miyamoto', nation: 'japan'},
    {name: 'Taylor', nation: 'usa'},
    {name: 'Olsen', nation: 'norway'},
    {name: 'Fernandez', nation: 'spain'},
    {name: 'Yamada', nation: 'japan'},
    {name: 'Wilson', nation: 'usa'},
    {name: 'Silva', nation: 'brazil'},
    {name: 'Muhammad', nation: 'pakistan'},
    {name: 'Liang', nation: 'china'},
    {name: 'Gonzales', nation: 'mexico'},
    {name: 'Lee', nation: 'usa'},
    {name: 'White', nation: 'usa'},
    {name: 'Kowalski', nation: 'poland'},
    {name: 'Mendoza', nation: 'mexico'},
    {name: 'Thompson', nation: 'usa'},
    {name: 'Huang', nation: 'china'},
    {name: 'Sakamoto', nation: 'japan'},
    {name: 'Smith', nation: 'usa'},
    {name: 'Zhang', nation: 'china'},
    {name: 'Petrov', nation: 'russia'},
    {name: 'Martin', nation: 'usa'},
    {name: 'Ferrari', nation: 'italy'},
    {name: 'Li', nation: 'china'},
    {name: 'Hernandez', nation: 'mexico'},
    {name: 'Jones', nation: 'usa'},
    {name: 'Wong', nation: 'china'},
    {name: 'Sanchez', nation: 'mexico'},
    {name: 'Muller', nation: 'germany'},
    {name: 'Kawasaki', nation: 'japan'},
    {name: 'Taylor', nation: 'usa'},
    {name: 'Nogueira', nation: 'brazil'},
    {name: 'Kumar', nation: 'india'}
]

fs.writeFile('content/action/names.json', JSON.stringify(names), 'utf-8', (err) => {
    if(err) console.log(err)
    else console.log('written names')
})
fs.writeFile('content/action/surnames.json', JSON.stringify(surnames), 'utf-8', (err) => {
    if(err) console.log(err)
    else console.log('written surnames')
})